### ISSUE TITLE
长时间运行小概率出错：IndexError: list index out of range  

### ISSUE THREAD

**Issue by QGB** [seishinkouki/oshwhub_autosign#10]
```
2022-12-26 05:09:00.889 | INFO     | oshwhub_autosign:auto_sign:101 - 开始获取未登录状态oshw cookies...                                                                                                                
Exception in thread Thread-1:                                            
Traceback (most recent call last):                                                
  File "/root/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()                                                                 
  File "/root/anaconda3/lib/python3.8/threading.py", line 870, in run            
    self._target(*self._args, **self._kwargs)                                                       
  File "/mnt/c/QGB/babun/cygwin/bin/qgb/U.py", line 7161, in schedule_background_run
    schedule.run_pending()                                                                    
  File "/home/qgb/.local/lib/python3.8/site-packages/schedule/__init__.py", line 780, in run_pending   
    default_scheduler.run_pending()                                                       
  File "/home/qgb/.local/lib/python3.8/site-packages/schedule/__init__.py", line 100, in run_pending
    self._run_job(job)                                                                           
  File "/home/qgb/.local/lib/python3.8/site-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()                                                                    
  File "/home/qgb/.local/lib/python3.8/site-packages/schedule/__init__.py", line 661, in run
    ret = self.job_func()                                                         
  File "/home/qgb/github/oshwhub_autosign/oshwhub_autosign.py", line 393, in main          
    my_user.auto_sign()                                                                       
  File "/home/qgb/github/oshwhub_autosign/oshwhub_autosign.py", line 104, in auto_sign                 
    _oshwhub_session = str(_oshw_cookies).replace("'", "").split(",")[1][17:]                 
IndexError: list index out of range                                                              
```

**Comment by seishinkouki** [comment]
更新了

**Comment by QGB** [comment]
@seishinkouki 

```
2023-01-10 05:09:01.025 | INFO     | oshwhub_autosign:auto_sign:101 - 开始获取未登录状态oshw cookies...
2023-01-10 05:09:01.793 | INFO     | oshwhub_autosign:auto_sign:129 - 开始获取CASAuth...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/c/QGB/babun/cygwin/bin/qgb/U.py", line 7161, in schedule_background_run
    import schedule
  File "/home/qgb/.local/lib/python3.8/site-packages/schedule/__init__.py", line 780, in run_pending
    default_scheduler.run_pending()
  File "/home/qgb/.local/lib/python3.8/site-packages/schedule/__init__.py", line 100, in run_pending
    self._run_job(job)
  File "/home/qgb/.local/lib/python3.8/site-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/home/qgb/.local/lib/python3.8/site-packages/schedule/__init__.py", line 661, in run
    ret = self.job_func()
  File "/home/qgb/github/oshwhub_autosign/oshwhub_autosign.py", line 393, in main
    my_user.auto_sign()
  File "/home/qgb/github/oshwhub_autosign/oshwhub_autosign.py", line 170, in auto_sign
    SESSION = passport_res.headers['Set-Cookie'].split(";")[-4].split("=")[-1]
  File "/home/qgb/.local/lib/python3.8/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'set-cookie'
In [8]: 

```

**Comment by QGB** [comment]
要搞个监控系统，程序出错自动重试&微信推送
