### ISSUE TITLE
今天开始出现错误 KeyError: 'set-cookie'

### ISSUE THREAD

**Issue by QGB** [seishinkouki/oshwhub_autosign#12]
```
2023-05-12 19:31:18.154 | INFO     | oshwhub_autosign:auto_sign:216 - 开始登陆...
2023-05-12 19:31:18.728 | INFO     | oshwhub_autosign:auto_sign:258 - 开始验证ticket...
2023-05-12 19:31:19.357 | INFO     | oshwhub_autosign:auto_sign:267 - 更新SESSION...
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/qgb/qgb/U.py", line 7252, in schedule_background_run
    schedule.run_pending()
  File "/usr/local/lib/python3.8/dist-packages/schedule/__init__.py", line 780, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python3.8/dist-packages/schedule/__init__.py", line 100, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python3.8/dist-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.8/dist-packages/schedule/__init__.py", line 661, in run
    ret = self.job_func()
  File "/home/qgb/github/oshwhub_autosign/oshwhub_autosign.py", line 402, in main
    my_user.auto_sign()
  File "/home/qgb/github/oshwhub_autosign/oshwhub_autosign.py", line 317, in auto_sign
    oshw_cookies['oshwhub_session'] = cookies2dict(oshw_res.headers['Set-Cookie'])['oshwhub_session']
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'set-cookie'
```

**Comment by seishinkouki** [comment]
https://github.com/seishinkouki/oshwhub_autosign/blob/be21a869d5c140c928a6c7799edd88de18ab1944/oshwhub_autosign.py#L74
因为立创的三天奖励下线, 这行的flag改0即可

**Comment by QGB** [comment]
可以在代码中自动判断一下吗
